[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
agent_program = "278wVm31qm5CVnjMszX7Ek5zWuWY4sFJtuEjt9N9Nivu"

[programs.localnet]
agent_program = "278wVm31qm5CVnjMszX7Ek5zWuWY4sFJtuEjt9N9Nivu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
