// ---------------------------------------------------------------------------
//  HTTP server. See server.h.
//
//  The page itself is shipped as an embedded asset (html/index.html). A
//  pre-build script (scripts/embed_assets.py, wired via platformio.ini)
//  turns it into a generated C file that exports a raw byte array plus its
//  length, which we feed straight to httpd_resp_send.
// ---------------------------------------------------------------------------
#include "server.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "cJSON.h"
#include "devcfg.h"
#include "social_x.h"
#include "esp_check.h"
#include "esp_http_server.h"
#include "esp_log.h"

static const char *TAG = "http";

// --- Embedded HTML (generated by scripts/embed_assets.py) -------------------
extern const char   index_html_start[];
extern const size_t index_html_len;

// --- Module state ------------------------------------------------------------
#define STATUS_MAX 64
#define REPLY_MAX  1024
// Bumped past devcfg's SVC_CUSTOM_MAX (4096) so a worst-case saveSettings
// POST — full custom-services JSON plus a few small fields — fits with
// room to spare for the surrounding JSON envelope.
#define BODY_MAX   8192
// /config GET serializes model + escaped persona (worst case 1024*6 = 6144)
// + servicesEnabled (512) + customServices (4096) into one envelope. That
// can blow past BODY_MAX, which would 500 the request and the web UI would
// silently render an empty form. Size the response buffer for that worst
// case so save → refresh round-trips reliably.
#define CONFIG_GET_MAX 16384

static httpd_handle_t         s_httpd   = NULL;
static server_say_handler_t   s_on_say  = NULL;
static char                   s_status[STATUS_MAX] = "booting";

// --- Helpers -----------------------------------------------------------------
static esp_err_t send_json(httpd_req_t *req, int code, const char *body) {
    httpd_resp_set_type(req, "application/json");
    httpd_resp_set_status(req, code == 200 ? "200 OK"
                             : code == 400 ? "400 Bad Request"
                                           : "500 Internal Server Error");
    return httpd_resp_sendstr(req, body);
}

// Escape a UTF-8 string into a JSON-string literal (without the surrounding
// quotes). Writes up to `cap-1` bytes + NUL. Truncates gracefully. Only
// handles the minimum set the phone UI cares about; adequate for chat text.
static void json_escape(const char *in, char *out, size_t cap) {
    size_t o = 0;
    for (const char *p = in; *p && o + 2 < cap; ++p) {
        unsigned char c = (unsigned char)*p;
        if      (c == '"' ) { if (o + 2 >= cap) break; out[o++] = '\\'; out[o++] = '"';  }
        else if (c == '\\') { if (o + 2 >= cap) break; out[o++] = '\\'; out[o++] = '\\'; }
        else if (c == '\n') { if (o + 2 >= cap) break; out[o++] = '\\'; out[o++] = 'n';  }
        else if (c == '\r') { if (o + 2 >= cap) break; out[o++] = '\\'; out[o++] = 'r';  }
        else if (c == '\t') { if (o + 2 >= cap) break; out[o++] = '\\'; out[o++] = 't';  }
        else if (c < 0x20)  { if (o + 6 >= cap) break;
                              o += (size_t)snprintf(out + o, cap - o,
                                                    "\\u%04x", c); }
        else                { out[o++] = (char)c; }
    }
    out[o] = '\0';
}

// Read the entire POST body into `buf` (capped at cap-1). Returns bytes
// read, or -1 on error.
static int read_body(httpd_req_t *req, char *buf, size_t cap) {
    size_t total = req->content_len;
    if (total >= cap) total = cap - 1;
    size_t read = 0;
    while (read < total) {
        int r = httpd_req_recv(req, buf + read, total - read);
        if (r <= 0) {
            if (r == HTTPD_SOCK_ERR_TIMEOUT) continue;
            return -1;
        }
        read += (size_t)r;
    }
    buf[read] = '\0';
    return (int)read;
}

// --- Handlers ----------------------------------------------------------------
static esp_err_t handle_root(httpd_req_t *req) {
    httpd_resp_set_type(req, "text/html; charset=utf-8");
    return httpd_resp_send(req, index_html_start, index_html_len);
}

static esp_err_t handle_state(httpd_req_t *req) {
    // Worst-case JSON escape of a control byte is \uXXXX (6x), so size the
    // escape buffer 6x the status capacity; the compiler uses the upper bound
    // when checking snprintf, not runtime content.
    char escaped[STATUS_MAX * 6 + 1];
    json_escape(s_status, escaped, sizeof(escaped));
    char body[sizeof(escaped) + 32];
    snprintf(body, sizeof(body), "{\"status\":\"%s\"}", escaped);
    return send_json(req, 200, body);
}

static esp_err_t handle_say(httpd_req_t *req) {
    if (req->content_len == 0 || req->content_len > BODY_MAX) {
        return send_json(req, 400, "{\"error\":\"bad body\"}");
    }
    char *user = malloc(req->content_len + 1);
    if (!user) return send_json(req, 500, "{\"error\":\"oom\"}");

    int n = read_body(req, user, req->content_len + 1);
    if (n < 0) { free(user); return send_json(req, 400, "{\"error\":\"recv\"}"); }

    // Trim trailing whitespace; the phone occasionally sends "\n" after text.
    while (n > 0 && (user[n-1] == ' ' || user[n-1] == '\n' ||
                     user[n-1] == '\r' || user[n-1] == '\t')) {
        user[--n] = '\0';
    }
    if (n == 0) { free(user); return send_json(req, 400, "{\"error\":\"empty\"}"); }

    // Dispatch to the registered AI handler. Synchronous — the phone waits
    // until we have a reply string. If no handler is wired up (phase 2 runs
    // before AI lands) we just return an empty reply so the UI stays sane.
    char reply[REPLY_MAX] = { 0 };
    server_say_handler_t cb = s_on_say;
    if (cb) cb(user, reply, sizeof(reply));
    free(user);

    char esc[REPLY_MAX * 2 + 16];
    json_escape(reply, esc, sizeof(esc));
    char body[sizeof(esc) + 32];
    snprintf(body, sizeof(body), "{\"reply\":\"%s\"}", esc);
    return send_json(req, 200, body);
}

// /config exposes the persisted settings the phone UI needs: LLM model,
// personality, custom x402 services library and the subset enabled. The
// two service fields are stored as raw JSON strings in NVS so we embed
// them directly in the response envelope rather than re-parsing just to
// serialise again — devcfg guarantees "[]" when nothing has been saved.
static esp_err_t handle_config_get(httpd_req_t *req) {
    const char *model    = devcfg_llm_model();
    const char *persona  = devcfg_personality();
    const char *svc_all  = devcfg_custom_services();
    const char *svc_on   = devcfg_services_enabled();

    // Worst-case JSON escape is 6x (a run of control bytes encoded as
    // \uXXXX). Personality is up to 1024 chars so a stack buffer would
    // be ~6 KB — the httpd task has 16 KB of stack but /say uses most
    // of it for TLS, so keep this off the stack.
    char *model_esc   = malloc(96 * 6 + 1);
    char *persona_esc = malloc(1024 * 6 + 1);
    char *body        = malloc(CONFIG_GET_MAX);
    if (!model_esc || !persona_esc || !body) {
        free(model_esc); free(persona_esc); free(body);
        return send_json(req, 500, "{\"error\":\"oom\"}");
    }
    json_escape(model,   model_esc,   96 * 6 + 1);
    json_escape(persona, persona_esc, 1024 * 6 + 1);

    int n = snprintf(body, CONFIG_GET_MAX,
                     "{\"model\":\"%s\",\"personality\":\"%s\","
                     "\"servicesEnabled\":%s,\"customServices\":%s}",
                     model_esc, persona_esc, svc_on, svc_all);
    esp_err_t err = (n > 0 && n < CONFIG_GET_MAX)
        ? send_json(req, 200, body)
        : send_json(req, 500, "{\"error\":\"body too large\"}");
    free(model_esc);
    free(persona_esc);
    free(body);
    return err;
}

// Phone UI POSTs a partial-update JSON object — any combination of
// model, personality, customServices (array), servicesEnabled (array).
// Arrays are re-serialised back to a string before hitting NVS so the
// storage layer stays opaque to cJSON.
static esp_err_t handle_config_post(httpd_req_t *req) {
    if (req->content_len == 0 || req->content_len > BODY_MAX) {
        // Drain partial body so the client gets a clean 400 instead of a
        // stalled connection reset.
        char scratch[256];
        int remaining = req->content_len;
        while (remaining > 0) {
            int r = httpd_req_recv(req, scratch,
                                   remaining < (int)sizeof(scratch)
                                       ? remaining : (int)sizeof(scratch));
            if (r <= 0) break;
            remaining -= r;
        }
        return send_json(req, 400, "{\"error\":\"bad body\"}");
    }

    char *buf = malloc(req->content_len + 1);
    if (!buf) return send_json(req, 500, "{\"error\":\"oom\"}");
    int n = read_body(req, buf, req->content_len + 1);
    if (n < 0) { free(buf); return send_json(req, 400, "{\"error\":\"recv\"}"); }

    cJSON *root = cJSON_Parse(buf);
    free(buf);
    if (!root) return send_json(req, 400, "{\"error\":\"json\"}");

    const cJSON *j_model   = cJSON_GetObjectItemCaseSensitive(root, "model");
    const cJSON *j_persona = cJSON_GetObjectItemCaseSensitive(root, "personality");
    const cJSON *j_svc_all = cJSON_GetObjectItemCaseSensitive(root, "customServices");
    const cJSON *j_svc_on  = cJSON_GetObjectItemCaseSensitive(root, "servicesEnabled");

    if (cJSON_IsString(j_model))   devcfg_set_llm_model(j_model->valuestring);
    if (cJSON_IsString(j_persona)) devcfg_set_personality(j_persona->valuestring);

    // cJSON_PrintUnformatted allocates — free before falling through.
    if (cJSON_IsArray(j_svc_all)) {
        char *s = cJSON_PrintUnformatted(j_svc_all);
        if (s) { devcfg_set_custom_services(s); cJSON_free(s); }
    }
    if (cJSON_IsArray(j_svc_on)) {
        char *s = cJSON_PrintUnformatted(j_svc_on);
        if (s) { devcfg_set_services_enabled(s); cJSON_free(s); }
    }

    cJSON_Delete(root);
    return send_json(req, 200, "{\"ok\":true}");
}

// --- Social / X handlers -----------------------------------------------------

// GET /social/x/state -> { "connected": bool, "handle"?: str }
static esp_err_t handle_x_state(httpd_req_t *req) {
    char body[160];
    if (devcfg_x_connected()) {
        snprintf(body, sizeof(body),
                 "{\"connected\":true,\"handle\":\"%s\"}",
                 devcfg_x_handle()[0] ? devcfg_x_handle() : "");
    } else {
        snprintf(body, sizeof(body), "{\"connected\":false}");
    }
    return send_json(req, 200, body);
}

// POST /social/x/begin -> { "auth_url": "..." }
static esp_err_t handle_x_begin(httpd_req_t *req) {
    char url[512];
    if (!social_x_begin(url, sizeof(url))) {
        return send_json(req, 500, "{\"error\":\"begin_failed\"}");
    }
    char body[600];
    snprintf(body, sizeof(body), "{\"auth_url\":\"%s\"}", url);
    return send_json(req, 200, body);
}

// POST /social/x/finish  body: { "code": "..." } -> { "ok": bool, ... }
static esp_err_t handle_x_finish(httpd_req_t *req) {
    char buf[2048];
    int len = httpd_req_recv(req, buf, sizeof(buf) - 1);
    if (len <= 0) return send_json(req, 400, "{\"error\":\"no_body\"}");
    buf[len] = 0;
    cJSON *root = cJSON_Parse(buf);
    if (!root) return send_json(req, 400, "{\"error\":\"bad_json\"}");
    cJSON *code = cJSON_GetObjectItem(root, "code");
    if (!cJSON_IsString(code) || !code->valuestring) {
        cJSON_Delete(root);
        return send_json(req, 400, "{\"error\":\"missing_code\"}");
    }
    char err[64] = {0};
    bool ok = social_x_finish(code->valuestring, err, sizeof(err));
    cJSON_Delete(root);
    if (!ok) {
        char body[160];
        snprintf(body, sizeof(body), "{\"ok\":false,\"error\":\"%s\"}", err);
        return send_json(req, 400, body);
    }
    char body[160];
    snprintf(body, sizeof(body),
             "{\"ok\":true,\"handle\":\"%s\"}",
             devcfg_x_handle()[0] ? devcfg_x_handle() : "");
    return send_json(req, 200, body);
}

// POST /social/x/disconnect -> { "ok": true }
static esp_err_t handle_x_disconnect(httpd_req_t *req) {
    social_x_disconnect();
    return send_json(req, 200, "{\"ok\":true}");
}

// --- Public API --------------------------------------------------------------
esp_err_t server_start(void) {
    if (s_httpd) return ESP_OK;

    httpd_config_t cfg = HTTPD_DEFAULT_CONFIG();
    cfg.server_port     = 80;
    cfg.max_uri_handlers = 12;
    cfg.lru_purge_enable = true;
    // The /say path runs the full AI pipeline on the httpd task — that's
    // up to four TLS handshakes (LLM, two Solana RPC calls, LLM retry)
    // plus cJSON/mbedtls scratch. Default 4 KB blows the canary; 16 KB
    // leaves room for the stack growth inside mbedtls_ssl_handshake().
    cfg.stack_size       = 16384;
    cfg.recv_wait_timeout = 10;
    cfg.send_wait_timeout = 10;

    ESP_RETURN_ON_ERROR(httpd_start(&s_httpd, &cfg), TAG, "httpd_start");

    static const httpd_uri_t uris[] = {
        { .uri = "/",       .method = HTTP_GET,  .handler = handle_root        },
        { .uri = "/state",  .method = HTTP_GET,  .handler = handle_state       },
        { .uri = "/say",    .method = HTTP_POST, .handler = handle_say         },
        { .uri = "/config", .method = HTTP_GET,  .handler = handle_config_get  },
        { .uri = "/config", .method = HTTP_POST, .handler = handle_config_post },
        { .uri = "/social/x/state",      .method = HTTP_GET,  .handler = handle_x_state      },
        { .uri = "/social/x/begin",      .method = HTTP_POST, .handler = handle_x_begin      },
        { .uri = "/social/x/finish",     .method = HTTP_POST, .handler = handle_x_finish     },
        { .uri = "/social/x/disconnect", .method = HTTP_POST, .handler = handle_x_disconnect },
    };
    for (size_t i = 0; i < sizeof(uris) / sizeof(uris[0]); ++i) {
        ESP_RETURN_ON_ERROR(httpd_register_uri_handler(s_httpd, &uris[i]),
                            TAG, "register %s", uris[i].uri);
    }

    ESP_LOGI(TAG, "listening on :80 (%u bytes of HTML embedded)",
             (unsigned)index_html_len);
    return ESP_OK;
}

void server_stop(void) {
    if (!s_httpd) return;
    httpd_stop(s_httpd);
    s_httpd = NULL;
}

void server_set_say_handler(server_say_handler_t h) { s_on_say = h; }

void server_set_status(const char *status) {
    if (!status) status = "";
    strlcpy(s_status, status, sizeof(s_status));
}
